# Generated by Django 4.2.6 on 2024-03-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_aaplstock_msftstock_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='stock_type',
            field=models.CharField(choices=[('Apple', 'Apple (AAPL)'), ('Microsoft', 'Microsoft (MSFT)')], max_length=15, verbose_name='Stock Type'),
        ),
    ]
