# Generated by Django 4.2.6 on 2024-03-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
        ),
    ]
