# Generated by Django 4.2.6 on 2024-03-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_trade_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='money_in_account',
            field=models.FloatField(default=1000.0),
        ),
    ]
