# Generated by Django 4.2.6 on 2024-03-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_trade_info_trades_stock_name_trades_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='total_pnl',
            field=models.FloatField(default=0),
        ),
    ]
