# Generated by Django 4.2.6 on 2024-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_money_in_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='trade_info',
            new_name='stock_name',
        ),
        migrations.AddField(
            model_name='trades',
            name='pnl',
            field=models.FloatField(default=0),
        ),
    ]
