# Generated by Django 4.2.6 on 2024-03-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_stocktype_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='stock_type',
            field=models.CharField(choices=[('Apple', 'Apple (AAPL)'), ('Microsoft', 'Microsoft (MSFT)')], max_length=15),
        ),
    ]
