# Generated by Django 4.2.6 on 2024-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_bacstock_jnjstock_jpmstock_pfestock_delete_metastock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='stock_type',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Microsoft', 'Microsoft'), ('Jhonson&Jhonson', 'Jhonson&Jhonson'), ('Pfizer', 'Pfizer'), ('JPMorgan', 'JPMorgan'), ('BankofAmerica', 'BankofAmerica')], max_length=15, verbose_name='Stock Type'),
        ),
    ]
