# Generated by Django 4.2.6 on 2024-05-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_adbestock_adsstock_amznstock_coststock_hdstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('Apple', 'Apple'), ('Microsoft', 'Microsoft'), ('Jhonson&Jhonson', 'Jhonson&Jhonson'), ('Pfizer', 'Pfizer'), ('BankofAmerica', 'BankofAmerica')], max_length=15, verbose_name='Stock Type')),
            ],
        ),
        migrations.DeleteModel(
            name='ADSStock',
        ),
    ]
